name: Upload Coverage Report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '36 18 * * *'

jobs:
  test-and-upload-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Intsall packages 
        run: |
          cd counter_app/
          npm i

      - name: Run tests with coverage
        run: npx vitest run --coverage
        working-directory: ./counter_app

      - name: Deploy coverage report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./counter_app/coverage
          destination_dir: coverage
