name: Upload Coverage Report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-upload-coverage:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: counter_app  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npx vitest run --coverage

      - name: Deploy coverage report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: counter_app/coverage 
          destination_dir: coverage
